title: <p align="center"> Praneta M </p>
logo: /assets/img/pranetaProfilepic.jpg

description:
  <p align="center">
  
  <a href="https://www.linkedin.com/in/praneta-m-66714961/">LinkedIn</a> |
  <a href="https://github.com/pranetasameer">GitHub</a>
  
  <br>   
  As a Java developer with a decade of experience in L3 support projects, I am now transitioning to the exciting world of AI and machine learning. 
  I have a solid foundation in object-oriented programming, data structures, algorithms, and software engineering principles, which I am now applying 
  to the development of AI and ML solutions.
  I have been learning and practicing various ML algorithms, such as linear regression, logistic regression, decision trees, random forests, support vector 
  machines, and neural networks. I am also familiar with data preprocessing, feature engineering, model selection and evaluation, and hyperparameter tuning techniques.
  In addition, I have experience with data visualization tools, such as Matplotlib and Seaborn, and data manipulation libraries, such as Pandas and NumPy. 
  I am also comfortable with SQL databases, such as Oracle and Postgres, and I have worked with RESTful APIs and learnt microservices architectures.
  As I continue to deepen my knowledge and skills in AI and ML, I am eager to apply them to real-world problems and contribute to cutting-edge projects 
  that push the boundaries of what is possible. I am a quick learner, a team player, and a problem solver, and I am excited about the opportunities 
  that lie ahead in this dynamic and rapidly evolving field.
  <br>
  </p>



theme: jekyll-theme-minimal
