title: <p align="center"> Praneta M </p>
logo: /assets/img/pranetaProfilepic.JPG

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/praneta-m-66714961/">LinkedIn</a> |
  <a href="https://github.com/pranetasameer">GitHub</a>
  
  <br>   
  Java| Machine Learning | Data Science
  <br>
  </p>



theme: jekyll-theme-minimal
