title: <p align="center"> Praneta M </p>
logo: /assets/img/pranetaProfilepic.jpg

description:
  <p align="center">
  
  <a href="https://www.linkedin.com/in/praneta-m-66714961/">LinkedIn</a> |
  <a href="https://github.com/pranetasameer">GitHub</a>
  
  <br>   
  As a Java developer with a decade of experience, I am now transitioning to the exciting world of AI and machine learning. 
  I have a solid foundation in object-oriented programming, data structures, algorithms, and software engineering principles, which I am now applying 
  to the development of AI and ML solutions.
  I have been learning and practicing various ML algorithms
  <br>
  </p>



theme: jekyll-theme-minimal
